name: devfest_flutter_app
description: Application for GDG DevFest

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.8.2+3
  firebase_auth: ^0.6.6
  firebase_messaging: ^2.1.0
  firebase_storage: ^1.0.4
  firebase_analytics: ^1.1.0
  intl: ^0.15.7
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.10.1
  url_launcher: ^4.0.3
  flutter_youtube: ^1.1.4
  google_sign_in: ^3.2.4
  cloud_functions: ^0.0.5
  equatable: ^0.1.6
  flutter_bloc: ^0.5.1
  google_maps_flutter: ^0.2.0

dev_dependencies:
  test: ^1.5.1
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/images/fon1.png
   - assets/images/speaker.jpg
   - assets/images/home.jpg
   - assets/images/team.jpg
   - assets/images/logo.svg
   - assets/images/logo.png
   - assets/images/logo_blue.png
   - assets/images/logo-monochrome.svg
   - assets/images/organizer-logo.svg
   - assets/images/organizer-logo-white.png
   - assets/images/google.svg
   - assets/icons/link-icon.svg
   - assets/icons/telegram.svg
   - assets/icons/facebook.svg
   - assets/icons/github.svg
   - assets/icons/gplus.svg
   - assets/icons/instagram.svg
   - assets/icons/linkedin.svg
   - assets/icons/twitter.svg
   - assets/icons/vkontakte.svg
   - assets/icons/website.svg
   - assets/icons/youtube.svg
   - assets/icons/gdg.svg
   - assets/icons/gde.svg
   - assets/icons/wtm.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
